### ISSUE TITLE
Help! Why there is no server on my website?

### ISSUE THREAD

**Issue by ComeOrDream** [mattwright324/hll-server-browser#1]
I have followed the BUILD.me and deplyed the website on my ubuntu. But why there is no server on the list? Does the port only used in this program is 4000?

**Comment by ComeOrDream** [comment]
![Uploading 2024-09-23_130346.png…]()

**Comment by ComeOrDream** [comment]
<img width="970" alt="2024-09-23_130346" src="https://github.com/user-attachments/assets/21ec653a-c0f0-475b-9fb1-8f4c31e43c85">

**Comment by ComeOrDream** [comment]
<img width="1017" alt="2024-09-23_130615" src="https://github.com/user-attachments/assets/694b09bc-65e8-42e7-abee-0a1023f17a7e">

**Comment by mattwright324** [comment]
Hey @ComeOrDream,

Sorry I'm only seeing this now but the server side script is restricted to my domain and localhost:4000, so changing the port to something else would cause it to not work. 

However, I only just moved the server side code from a non-public heroku instance to a public github repo here which you can now also run locally. The old heroku server url should no longer work.

https://github.com/mattwright324/hll-server-browser-socket

You would just need to change the connect url on the site to match your local node.js socket instance.

**Comment by ComeOrDream** [comment]
OK，I'll try it. Thank you.
